
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS student;
CREATE TABLE student (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, first_name VARCHAR (32), last_name VARCHAR (32), email VARCHAR (100) UNIQUE, phone VARCHAR (25), course VARCHAR (100));

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
